.\" Manpage for nudoku.
.TH man 8 "07 April 2015" "2.1" "nudoku man page"
.SH NAME
nudoku \- ncurses based sudoku game
.SH SYNOPSIS
nuseradd [OPTIONS]
.SH DESCRIPTION
nudoku is a ncurses based sudoku game. Perfect to relax a little or just waste some time when you are on the console.
.SH OPTIONS
nudoku does not take any options.

.BR \-h
Print help.

.BR \-v
Display version information.

.BR \-c
Do not use colors. Black and white mode.

.BR \-d
Choose difficulty.
Available options are: easy, normal, hard
.SH BUGS
No known bugs.
.SH AUTHOR
Michael Vetter (g.bluehut@gmail.com)
