/*
vim: noexpandtab:ts=4:sts=4:sw=4

nudoku

Copyright (C) 2014 - 2019 Michael "jubalh" Vetter - jubalh _a-t_ iodoru.org

LICENCE:
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* INCLUDES */
#include <cairo.h>				/* cairo_*() */
#include <cairo-pdf.h>			/* cairo_pdf_surface_create */
#include <stdio.h>				/* snprintf() */
#include "sudoku.h"				/* sudoku functions */

/* FUNCTIONS */

void draw_grid(const char* stream, cairo_t *cr, int offset_x, int offset_y)
{
	int rectangle_size = 50;

	// small rectangles
	cairo_set_line_width(cr, 2);
	for (int x=0; x < 9; x++)
	{
		for (int y=0; y < 9; y++)
		{
			cairo_rectangle(cr, offset_x + x*rectangle_size, offset_y + y*rectangle_size, rectangle_size, rectangle_size);
		}
	}
	cairo_stroke(cr);

	// large rectangles
	cairo_set_line_width(cr, 4);
	for (int x=0; x < 3; x++)
	{
		for (int y=0; y < 3; y++)
		{
			cairo_rectangle(cr, offset_x + x * rectangle_size * 3, 30 + offset_y * rectangle_size * 3, rectangle_size * 3, rectangle_size * 3);
		}
	}
	cairo_stroke(cr);

	// numbers
	cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
	cairo_set_font_size(cr, 25.0);
	int c;
	char tmp_str[2];
	for(int row=0; row < 9; row++)
	{
		for(int	col=0; col < 9; col++)
		{
			c = stream[row*9+col];
			if (c != '.')
			{
				cairo_move_to(cr, offset_x + rectangle_size/3 + rectangle_size * row, offset_y + rectangle_size/1.5 + rectangle_size * col);
				snprintf(tmp_str, 2, "%c", c);
				cairo_show_text(cr, tmp_str);
			}
		}
	}
}

void generate_output(const char *stream, const char *difficulty)
{
	cairo_surface_t *surface;
	cairo_t *cr;
	surface = cairo_pdf_surface_create("pdffile.pdf", 1024, 1024);
	cr = cairo_create(surface);

	cairo_set_source_rgb(cr, 0, 0, 0);
	cairo_set_line_cap(cr, CAIRO_LINE_CAP_SQUARE);

	cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
	cairo_set_font_size(cr, 15.0);

	// difficulty is dependant on translation. let's be safe here and use snprintf() in case it's very long.
	char tmp_str[512];
	snprintf(tmp_str, 512, "sudoku level %s generated by nudoku - http://jubalh.github.io/nudoku/", difficulty);

	cairo_move_to(cr, 10.0, 20.0);
	cairo_show_text(cr, tmp_str);

	/*
	cairo_set_line_width(cr, 5);
	cairo_move_to(cr, 5.0, 70);
	cairo_line_to(cr, 455, 70);
	cairo_stroke(cr);
	*/

	draw_grid(stream, cr, 30, 30);
	draw_grid(stream, cr, 500, 30);

	cairo_show_page(cr);
	cairo_destroy(cr);
	cairo_surface_destroy(surface);
}
