/*
vim: noexpandtab:ts=4:sts=4:sw=4

nudoku

Copyright (C) 2014 - 2024 Michael "jubalh" Vetter - jubalh _a-t_ iodoru.org

LICENCE:
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* INCLUDES */
#include <cairo.h>				/* cairo_*() */
#include <cairo-pdf.h>			/* cairo_pdf_surface_create */
#include <stdio.h>				/* snprintf() */
#include <stdlib.h>				/* free() */
#include "sudoku.h"				/* sudoku functions */
#include "utils.h"				/* utility definitions */

typedef struct {
	int x;
	int y;
} DUPLE_INT;

typedef struct {
	double x;
	double y;
} DUPLE_DOUBLE;

#define RECT_SIZE(type) ((type) 50)
#define SUDOKU_SIZE(type) ((RECT_SIZE(type)) * ((type) 9))
#define SUDOKU_SPACE(type, pad) ((SUDOKU_SIZE(type)) + ((type) pad))

/* FUNCTIONS */

void draw_grid(const char* stream, cairo_t *cr)
{
	int rectangle_size = RECT_SIZE(int);

	// small rectangles
	cairo_set_line_width(cr, 1);
	for (int x=0; x < 9; x++)
	{
		for (int y=0; y < 9; y++)
		{
			cairo_rectangle(cr, x*rectangle_size, y*rectangle_size, rectangle_size, rectangle_size);
		}
	}
	cairo_stroke(cr);

	// large rectangles
	cairo_set_line_width(cr, 4);
	for (int x=0; x < 3; x++)
	{
		for (int y=0; y < 3; y++)
		{
			cairo_rectangle(cr, x * rectangle_size * 3, y * rectangle_size * 3, rectangle_size * 3, rectangle_size * 3);
		}
	}
	cairo_stroke(cr);

	// numbers
	cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
	cairo_set_font_size(cr, 25.0);
	int c;
	char tmp_str[2];
	for(int row=0; row < 9; row++)
	{
		for(int	col=0; col < 9; col++)
		{
			c = stream[row*9+col];
			if (c != '.')
			{
				cairo_move_to(cr, rectangle_size/3 + rectangle_size * row, rectangle_size/1.5 + rectangle_size * col);
				snprintf(tmp_str, 2, "%c", c);
				cairo_show_text(cr, tmp_str);
			}
		}
	}
}

// Use Cairo's transformation matrix to get how many sudokus fit in a page. The matrix must NOT have rotations applied!
static DUPLE_INT get_no_sudokus_fit(cairo_t *cr, PAPER_SIZE dd_ps, DUPLE_INT di_initial_pad, DUPLE_INT di_intra_pad) {
	cairo_matrix_t ctm;
	cairo_get_matrix(cr, &ctm);

	// First sudoku uses initial margin as padding.
	double fsx = SUDOKU_SPACE(double, di_initial_pad.x);
	double fsy = SUDOKU_SPACE(double, di_initial_pad.y);

	cairo_matrix_transform_distance(&ctm, &fsx, &fsy);

	// Other sudokus use uniform intra-spacing.
	double sx = SUDOKU_SPACE(double, di_intra_pad.x);
	double sy = SUDOKU_SPACE(double, di_intra_pad.y);

	cairo_matrix_transform_distance(&ctm, &sx, &sy);

	// No. sudokus = ((Page length - first sudoku length) / other sudokus length) + 1
	// The +1 accounts for the first sudoku that was subtracted from the page length.

	double fx = ((dd_ps.width - fsx) / sx) + 1;
	double fy = ((dd_ps.height - fsy) / sy) + 1;

	DUPLE_INT dr = { (int) fx, (int) fy };
	return dr;
}

static void prepare_new_page(cairo_t *cr, int difficulty, bool first_page) {
	cairo_set_source_rgb(cr, 0, 0, 0);
	cairo_set_line_cap(cr, CAIRO_LINE_CAP_SQUARE);

	cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
	cairo_set_font_size(cr, 10.0);

	// difficulty is dependant on translation. let's be safe here and use snprintf() in case it's very long.
	char tmp_str[512];
	snprintf(tmp_str, 512, "sudoku level: %s", difficulty_to_str(difficulty));

	if (!first_page)
		cairo_scale(cr, 2.0, 2.0);

	cairo_move_to(cr, 50.0, 70.0);
	cairo_show_text(cr, tmp_str);
	cairo_move_to(cr, 50.0, 80.0);
	cairo_show_text(cr, "generated by nudoku - http://jubalh.github.io/nudoku/");

	if (first_page)
		cairo_save(cr);

	cairo_scale(cr, 0.5, 0.5);
}

static int finish_pdf_generation(cairo_surface_t *surface, cairo_t *cr, bool successful) {
	cairo_restore(cr);

	if (successful)
		cairo_show_page(cr);

	cairo_destroy(cr);
	cairo_surface_destroy(surface);

	return successful ? EXIT_SUCCESS : EXIT_FAILURE;
}

int generate_pdf(int difficulty, int sudokus_count, PAPER_SIZE paperSize, const char* filename)
{
	cairo_surface_t *surface;
	cairo_t *cr;

	PAPER_SIZE ps_points = papersize_normalize(paperSize);
	surface = cairo_pdf_surface_create(filename, ps_points.width, ps_points.height);
	cr = cairo_create(surface);

	prepare_new_page(cr, difficulty, true);

	DUPLE_INT di_initial_pad = { 100, 270 };
	DUPLE_INT di_intra_pad = { 100, 150 };

	DUPLE_INT d_fit = get_no_sudokus_fit(cr, ps_points, di_initial_pad, di_intra_pad);

	if (d_fit.x <= 0 || d_fit.y <= 0) {
		printf(_("ERROR: Page dimensions are too small for sudokus to fit!\n"));
		printf(_("Please check the dimensions provided in '-S' and try again.\n"));

		return finish_pdf_generation(surface, cr, false);
	}

	int no_sudokus_per_page = d_fit.x * d_fit.y;

	for (int i=0; i < sudokus_count; i++)
	{
		int cur_sudoku_col = (i % no_sudokus_per_page) % d_fit.x;
		int cur_sudoku_row = (i % no_sudokus_per_page) / d_fit.x;

		DUPLE_INT start = {
			di_initial_pad.x + (cur_sudoku_col * SUDOKU_SPACE(int, di_intra_pad.x)),
			di_initial_pad.y + (cur_sudoku_row * SUDOKU_SPACE(int, di_intra_pad.y))
		};

		cairo_translate(cr, start.x, start.y);

		char* stream;
		stream = generate_puzzle(difficulty);

#ifdef DEBUG
		printf("%d: %s\n", i, stream);
#endif // DEBUG

		draw_grid(stream, cr);

		cairo_translate(cr, -start.x, -start.y);

		if ((i + 1) < sudokus_count && (i + 1) % no_sudokus_per_page == 0) {
			// Show current page
			cairo_show_page(cr);
			prepare_new_page(cr, difficulty, false);
		}

		free(stream);
	}

	return finish_pdf_generation(surface, cr, true);
}

void generate_png(int difficulty, char* filename)
{
	cairo_surface_t *surface;
	cairo_t *cr;

	surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 453, 453);
	cr = cairo_create(surface);

	cairo_set_source_rgb(cr, 0, 0, 0);
	cairo_set_line_cap(cr, CAIRO_LINE_CAP_SQUARE);

	cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
	cairo_set_font_size(cr, 10.0);

	char* stream;
	stream = generate_puzzle(difficulty);

	cairo_translate(cr, 2, 2);
	draw_grid(stream, cr);
	cairo_surface_write_to_png(surface, filename);

	cairo_destroy(cr);
	cairo_surface_destroy(surface);

	free(stream);
}

int generate_output(int difficulty, char* filename, int sudokuCount, bool isPDF, PAPER_SIZE paperSize)
{
	int exit_code = EXIT_SUCCESS;

	if (isPDF)
	{
		exit_code = generate_pdf(difficulty, sudokuCount, paperSize, filename);
	} else {
		generate_png(difficulty, filename);
	}

	return exit_code;
}
